### ISSUE TITLE
no lwjgl64 in java.library.path

### ISSUE THREAD

**Issue by ThePenguin-developer** [Badbird-5907/mcp_1.12.2#1]
I keep getting this error when trying to run mcp 1.12.2 

Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:3266)
	at net.minecraft.client.main.Main.main(Main.java:39)
	at Start.main(Start.java:11)
  
from what it looks like it cant fin lightweight game library but it IS there so help

**Comment by Badbird5907** [comment]
The solution's on google
